// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDR6U2fuWvPh8CLvP0QlnTeuGpvgXGHOQ',
    appId: '1:580696777688:web:98c09c22077e630d3988ad',
    messagingSenderId: '580696777688',
    projectId: 'fitme-cac8e',
    authDomain: 'fitme-cac8e.firebaseapp.com',
    storageBucket: 'fitme-cac8e.firebasestorage.app',
    measurementId: 'G-FQ6N6MW9FQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzzCKKTgD3RPowUHO6mb2q_sF-D2Ih_QE',
    appId: '1:580696777688:android:cde4b11996120e413988ad',
    messagingSenderId: '580696777688',
    projectId: 'fitme-cac8e',
    storageBucket: 'fitme-cac8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZtLiJg4T4TXcovY2PEXQpd2FVK1lM5Ck',
    appId: '1:580696777688:ios:64729246dd4213383988ad',
    messagingSenderId: '580696777688',
    projectId: 'fitme-cac8e',
    storageBucket: 'fitme-cac8e.firebasestorage.app',
    iosBundleId: 'ir.almaseman.shahrzad',
  );
}
